import 'package:flutter/material.dart';

class LanguageViewModel extends ChangeNotifier {
  Locale _currentLocale = const Locale('vi');
  Locale get currentLocale => _currentLocale;

  final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'app_title': 'Hôm Nay Ăn Gì?',
      'home': 'Trang chủ',
      'feed': 'Bảng tin',
      'search': 'Tìm kiếm',
      'restaurants': 'Gợi ý quán',
      'menu': 'Thực đơn',
      'profile': 'Hồ sơ',
      'what_to_eat': 'HÔM NAY ĂN GÌ?',
      'swipe_more': 'Vuốt để xem tiếp!',
      'settings': 'Cài đặt',
      'edit_profile': 'Chỉnh sửa hồ sơ',
      'language': 'Ngôn ngữ',
      'apply': 'Áp dụng',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'active': 'Đang áp dụng',
      'draft': 'Nháp',
      'history': 'Lịch sử',
      'all': 'Tất cả',
      'personal': 'Cá nhân',
      'promo': 'Khuyến mãi',
      'updates': 'Tin mới',
      'add_menu': 'Tạo thực đơn mới',
      'my_photos': 'ẢNH CỦA BẠN',
      'logout': 'Đăng xuất',
      'login': 'Đăng nhập',
      'search_hint': 'Tìm tên món ăn...',
      'today_suggestion': 'Gợi ý hôm nay',
      'popular_dishes': 'Món ăn phổ biến',
      'view_all': 'Xem tất cả',
      'trending': 'Xu hướng',
      'newest': 'Mới nhất',
      'near_you': 'Gần bạn',
      'likes': 'lượt thích',
      'comments': 'Bình luận',
      'share': 'Chia sẻ',
      'calories': 'Calo',
      'minutes': 'phút',
      'difficulty': 'Độ khó',
      'tasks': 'TÁC VỤ',
      'personalization': 'CÁ NHÂN HOÁ',
      'account': 'TÀI KHOẢN',
      'ai_assistant': 'Trợ lý AI Gemini',
      'restaurant_suggest': 'Gợi Ý Quán Ăn',
      'my_menu': 'Thực Đơn Của Tôi',
      'saved_recipes': 'Công Thức Đã Lưu',
      'random_dish': 'Ăn Theo Ý Trời',
      'diet_mode': 'Chế độ ăn của tôi',
      'allergy': 'Dị ứng & Kiêng khem',
      'health_stats': 'Chỉ số BMI & Sức khỏe',
      'about_us': 'Về Chúng Tôi',
      'post': 'Đăng',
      'new_post': 'Bài đăng mới',
      'photo_gallery': 'Chọn từ thư viện',
      'take_photo': 'Chụp ảnh',
      'enter_caption': 'Bạn đang nghĩ gì?',
      'location': 'Vị trí',
      'notifications': 'Thông báo',
      'read_all': 'Đọc tất cả',
      'no_notifications': 'Không có thông báo nào.',
      'filter': 'Bộ lọc',
      'clear_all': 'Xóa tất cả',
      'saved_filters': 'Bộ lọc đã lưu',
      'cooking_time': 'Thời gian nấu',
      'region': 'Vùng miền',
      'weather': 'Thời tiết',
      'mood': 'Tâm trạng',
      'ai_assistant_title': 'Trợ lý AI Trực Tuyến',
      'reset_chat': 'Làm mới cuộc trò chuyện',
      'chat_hint': 'Nhập câu hỏi cho trợ lý AI...',
      'total_calories': 'Tổng Calo',
      'dishes_count': 'Món ăn',
      'status': 'Trạng thái',
      'dish_list': 'DANH SÁCH MÓN ĂN',
      'apply_now': 'ÁP DỤNG NGAY',
      'complete': 'HOÀN THÀNH',
      'delete_plan': 'Xóa thực đơn?',
      'confirm_delete': 'Bạn có chắc chắn muốn xóa thực đơn này không?',
      'delete': 'Xóa',
    },
    'en': {
      'app_title': 'What to Eat Today?',
      'home': 'Home',
      'feed': 'Social',
      'search': 'Search',
      'restaurants': 'Nearby',
      'menu': 'Meal Plan',
      'profile': 'Profile',
      'what_to_eat': 'WHAT TO EAT TODAY?',
      'swipe_more': 'Swipe to see more!',
      'settings': 'Settings',
      'edit_profile': 'Edit Profile',
      'language': 'Language',
      'apply': 'Apply',
      'save': 'Save',
      'cancel': 'Cancel',
      'active': 'Active',
      'draft': 'Draft',
      'history': 'History',
      'all': 'All',
      'personal': 'Personal',
      'promo': 'Promo',
      'updates': 'News',
      'add_menu': 'Create new plan',
      'my_photos': 'MY PHOTOS',
      'logout': 'Logout',
      'login': 'Login',
      'search_hint': 'Search dishes...',
      'today_suggestion': 'Today\'s Suggestion',
      'popular_dishes': 'Popular Dishes',
      'view_all': 'View All',
      'trending': 'Trending',
      'newest': 'Newest',
      'near_you': 'Near You',
      'likes': 'likes',
      'comments': 'Comments',
      'share': 'Share',
      'calories': 'Calo',
      'minutes': 'mins',
      'difficulty': 'Difficulty',
      'tasks': 'TASKS',
      'personalization': 'PERSONALIZATION',
      'account': 'ACCOUNT',
      'ai_assistant': 'AI Gemini Assistant',
      'restaurant_suggest': 'Restaurant Suggestions',
      'my_menu': 'My Meal Plan',
      'saved_recipes': 'Saved Recipes',
      'random_dish': 'Random Dish',
      'diet_mode': 'My Diet Mode',
      'allergy': 'Allergies & Diet',
      'health_stats': 'BMI & Health Stats',
      'about_us': 'About Us',
      'post': 'Post',
      'new_post': 'New Post',
      'photo_gallery': 'Gallery',
      'take_photo': 'Camera',
      'enter_caption': 'What\'s on your mind?',
      'location': 'Location',
      'notifications': 'Notifications',
      'read_all': 'Read All',
      'no_notifications': 'No notifications.',
      'filter': 'Filter',
      'clear_all': 'Clear All',
      'saved_filters': 'Saved Filters',
      'cooking_time': 'Cooking Time',
      'region': 'Region',
      'weather': 'Weather',
      'mood': 'Mood',
      'ai_assistant_title': 'AI Assistant Online',
      'reset_chat': 'Reset Conversation',
      'chat_hint': 'Ask AI assistant something...',
      'total_calories': 'Total Calories',
      'dishes_count': 'Dishes',
      'status': 'Status',
      'dish_list': 'DISH LIST',
      'apply_now': 'APPLY NOW',
      'complete': 'COMPLETE',
      'delete_plan': 'Delete plan?',
      'confirm_delete': 'Are you sure you want to delete this plan?',
      'delete': 'Delete',
    },
  };

  void setLocale(Locale locale) {
    _currentLocale = locale;
    notifyListeners();
  }

  String t(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }
}
