name: Flutter

on:
  push:
    branches: ["main","hieu"]
  pull_request:
    branches: ["main", "hieu"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Check Flutter installation
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get
        
      - name: Create dummy .env file
        run: |
          mkdir -p assets
          touch assets/.env
          
      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test
